# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf769832a5c7207c3ec0b95bf0b404506e237a9ec2be45c627b5c3e883dab84073c3385c8440aa50e7028b40ae57a4c99f2f69327edc9a2f6664a9f2a8a1422f

test:
  secret_key_base: d56e07d68aa2669d85e3a44fa9dcbb8ee473ddc218a405991dda182ddd4db7d79f27fe4ac8d04013935978201e52a77b98f7fdeae95b6741f9410b0f1c97034b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
